added additional Steps.

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -6,15 +6,98 @@
 trigger:
 - master
 - Next
+variables:
+- group: 'Platform Release Variables'
 
 pool:
   vmImage: ubuntu-latest
+workspace:
+  clean: all
 
 steps:
-- script: echo Hello, world!
-  displayName: 'Run a one-line script'
+- checkout: self
+  persistCredentials: true
+  clean: true
 
 - script: |
-    echo Add other tasks to build, test, and deploy your project.
-    echo See https://aka.ms/yaml
-  displayName: 'Run a multi-line script'
+    #!/bin/bash
+    COMMIT_ID=$(git ls-remote --head --exit-code origin Next | cut -f 1 | head -n 1)
+    if [ -z "$(git log | grep $COMMIT_ID)" ]
+    then
+        echo "false"
+        echo "CI failed, Your branch $(Build.SourceBranch) is behind of Next branch changes, Kindly merge the changes from Next branch and rerun the pipeline"
+        exit 1
+    else
+        echo "true"
+    fi
+  condition: not(or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/Next'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix')))
+  displayName: "Check if Branch is in Sync"
+
+- task: NodeTool@0
+  inputs:
+    versionSpec: '12.20.x'
+  displayName: 'Use Node 12'
+
+- task: CmdLine@2
+  inputs:
+    script: |
+      #!/bin/bash
+      git config --global user.email "buildagent@emgage.com"
+      git config --global user.name "Automated VSTS Build Server"
+      BRANCH=$(echo $(Build.SourceBranch) | sed 's/refs\/heads\///')
+      echo "Checking out $BRANCH"
+      git checkout $BRANCH
+  displayName: 'Attach branch'
+  condition: not(eq(variables['Build.SourceBranchName'], 'merge'))
+
+- script: |
+    echo "@emgage:=registry" > .npmrc
+    echo "//registry.npmjs.org/:_authToken=$(NPM_TOKEN)" >> .npmrc
+  displayName: "Write NPMRC"
+
+- task: CmdLine@2
+  inputs:
+    script: |
+      npm install
+      npm rebuild node-sass
+  displayName: 'Npm Install'
+
+- task: CmdLine@2
+  inputs:
+    script: 'npm run build-dev'
+  displayName: 'Npm Install'
+
+- task: CmdLine@2
+  inputs:
+    script: |
+      #!/bin/bash
+      lib_path='cdn/engage-ui@next/lib'
+      git update-index --assume-unchanged .npmrc
+      if [ "$(Build.SourceBranchName)" == "master" ]
+      then
+          npm version --no-git-tag-version minor
+          npm publish --tag latest
+          lib_path='cdn/engage-ui@latest/lib'
+      else
+          npm version --no-git-tag-version prerelease
+          npm publish --tag next
+      fi
+      git add .
+      git commit -m "chore: Release [skip ci]" --no-verify
+      git push
+      echo "##vso[task.setvariable variable=engageui]$lib_path"
+  displayName: 'Tag and Publish'
+  condition: and(not(eq(startsWith(variables['Build.SourceVersionMessage'], 'chore: Release'))), eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/Next'))
+
+- task: S3Upload@1
+  inputs:
+    awsCredentials: 'AWS Connection'
+    regionName: 'us-west-2'
+    bucketName: 'emgage.software'
+    sourceFolder: '$(System.DefaultWorkingDirectory)'
+    globExpressions: 'lib/+(EngageUI.js|DeliciousTheme.js)'
+    targetFolder: '$(engageui)'
+    filesAcl: 'public-read'
+    flattenFolders: true
+  condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/Next'))
+  displayName: 'Copy to S3'
